In [87]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [88]:
columns = ["lettr", "x-box", "y-box", "width", "height", "onpix", "x-bar","y-bar", "x2bar", "y2bar", "xybar", "x2ybr", "xy2br", "x-ege", "xegvy","y-ege", "yegvx"]

In [89]:
df = pd.read_csv('/content/letter-recognition.data',names=columns)

In [90]:
df

lettr  x-box  y-box  width  height  onpix  x-bar  y-bar  x2bar  y2bar  \
0         T      2      8      3       5      1      8     13      0      6   
1         I      5     12      3       7      2     10      5      5      4   
2         D      4     11      6       8      6     10      6      2      6   
3         N      7     11      6       6      3      5      9      4      6   
4         G      2      1      3       1      1      8      6      6      6   
...     ...    ...    ...    ...     ...    ...    ...    ...    ...    ...   
19995     D      2      2      3       3      2      7      7      7      6   
19996     C      7     10      8       8      4      4      8      6      9   
19997     T      6      9      6       7      5      6     11      3      7   
19998     S      2      3      4       2      1      8      7      2      6   
19999     A      4      9      6       6      2      9      5      3      1   

       xybar  x2ybr  xy2br  x-ege  xegvy  y-ege  yegvx  
0          6     10      8      0      8      0      8  
1         13      3      9      2      8      4     10  
2         10      3      7      3      7      3      9  
3          4      4     10      6     10      2      8  
4          6      5      9      1      7      5     10  
...      ...    ...    ...    ...    ...    ...    ...  
19995      6      6      4      2      8      3      7  
19996     12      9     13      2      9      3      7  
19997     11      9      5      2     12      2      4  
19998     10      6      8      1      9      5      8  
19999      8      1      8      2      7      2      8  

[20000 rows x 17 columns]

In [91]:
df.shape

(20000, 17)

In [93]:
x = df.drop(df.columns[0],axis = 1).values

In [94]:
y = df[df.columns[0]].values

In [96]:
x.shape

(20000, 16)

In [97]:
y.shape

(20000,)

In [98]:
np.unique(y)

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype=object)

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [100]:
x_train[0]

array([ 4,  9,  5,  7,  3,  5,  7,  6,  5, 10,  8, 10,  2,  8,  5,  9])

In [101]:
y_train[0]

'G'

In [102]:
class_names = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

In [103]:
x_test[10]

array([ 2, 10,  4,  7,  1, 10, 14,  1,  6,  4, 11,  9,  0,  8,  0,  8])

In [104]:
y_test[10]

'T'

In [105]:
x_train = x_train/255
x_test = x_test/255

In [106]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [107]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [108]:
model = Sequential()
model.add(Dense(512,activation='relu',input_shape = (x_train[0].shape)))
model.add(Dropout(0.2))
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(26,activation = 'softmax'))
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 512)               8704      
                                                                 
 dropout_6 (Dropout)         (None, 512)               0         
                                                                 
 dense_10 (Dense)            (None, 256)               131328    
                                                                 
 dropout_7 (Dropout)         (None, 256)               0         
                                                                 
 dense_11 (Dense)            (None, 26)                6682      
                                                                 
Total params: 146,714
Trainable params: 146,714
Non-trainable params: 0
_________________________________________________________________


In [109]:
model.fit(x_train,y_train,epochs = 50,batch_size=128,verbose=1,validation_data=(x_test,y_test))


Epoch 1/50
125/125 [==============================] - 2s 9ms/step - loss: 3.1467 - accuracy: 0.1318 - val_loss: 2.8118 - val_accuracy: 0.2570
Epoch 2/50
125/125 [==============================] - 1s 7ms/step - loss: 2.3955 - accuracy: 0.3124 - val_loss: 2.0901 - val_accuracy: 0.4065
Epoch 3/50
125/125 [==============================] - 1s 7ms/step - loss: 1.9553 - accuracy: 0.4116 - val_loss: 1.7667 - val_accuracy: 0.4865
Epoch 4/50
125/125 [==============================] - 1s 7ms/step - loss: 1.7427 - accuracy: 0.4649 - val_loss: 1.6240 - val_accuracy: 0.5148
Epoch 5/50
125/125 [==============================] - 1s 8ms/step - loss: 1.6269 - accuracy: 0.5006 - val_loss: 1.5102 - val_accuracy: 0.5558
Epoch 6/50
125/125 [==============================] - 1s 8ms/step - loss: 1.5323 - accuracy: 0.5356 - val_loss: 1.4491 - val_accuracy: 0.5775
Epoch 7/50
125/125 [==============================] - 1s 7ms/step - loss: 1.4645 - accuracy: 0.5592 - val_loss: 1.3640 - val_accuracy: 0.5982
Epoch 

In [110]:
x_test[10]

array([0.00784314, 0.03921569, 0.01568627, 0.02745098, 0.00392157,
       0.03921569, 0.05490196, 0.00392157, 0.02352941, 0.01568627,
       0.04313725, 0.03529412, 0.        , 0.03137255, 0.        ,
       0.03137255])

In [111]:
y_test[10]

19

In [112]:
predictions = model.predict(x_test)

125/125 [==============================] - 0s 1ms/step


In [113]:
index = 10
print(predictions[index])
final_value=np.argmax(predictions[index])
print("Actual label :",y_test[index])
print("Predicted label",final_value)
print("Class A-Z",class_names[final_value])

[5.3781507e-10 3.1128798e-24 1.8746069e-10 2.7172772e-17 3.1119662e-16
 1.6934453e-06 4.0577216e-21 2.7337544e-11 1.0114093e-03 1.7807898e-10
 4.3754293e-12 2.8943522e-14 1.1824132e-24 9.8803534e-14 3.8782319e-21
 3.3620906e-13 1.9293113e-15 7.8133622e-26 4.2456719e-10 9.9836242e-01
 9.2423527e-11 1.3952105e-06 1.3722227e-20 3.4882592e-05 5.8824924e-04
 5.2670685e-22]
Actual label : 19
Predicted label 19
Class A-Z T
